apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mydeployments.example.com
spec:
  group: example.com
  names:
    kind: MyDeployment
    plural: mydeployments
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true

